
spring.application.name=Annuaire
server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/annuaire2
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

database.name=annuaire2

node.script.path=src/main/resources/scripts/cnom.js
python.script.path=src/main/resources/scripts/clean.py
node.data.folder=../db/data
node.changes.folder=../db/changes
node.backup.folder=../db/backups
python.clean.folder=../db/clean
node.api.url=https://website.ordre-medecins.com/api/MedecinApi?Nom=&Prenom=&Spec=&Ville=


jwt.secret-key=da7828fcebf210e8ffbfe85bcecf8dbbadece2f9122fcc70e72e6883b08ccd50d8711ee2eae8c17c989f128125929550d0cfef3a2b2f86bf867bd54fe2aaefe3e2c2dcd6c21bdc82d1a1418012647f61ef69b04d8be3c08ac16ea4bb146a2ad95cd8522ced3c6968f7c58496123528e0cbc18beec98eaf872bfff343cf900ac860f18c9338859aa41ced7cd303d7bbc6767ff616c6f3e8ac23a650151a6e2f77f8ada18ea68efd136f1ce29a426d0ecfb0c9b08e4ee2ebe298bf374e7617dc06dcc28e69e0c2637db3e920ee10144dd71f9d74b13da5ab4bad5a7a6a8a3d62c64a34c9ce1954266c8395cca70e22e8b2c063dcfd2c321480a69df3a908a84161
jwt.expiration=3600000
jwt.refresh-expiration=604800000

backup.tables=healthcare_professional,additional_attributes_ps,backup_history

mysql.dump.path=${MYSQLDUMP_PATH:C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin\\mysqldump.exe}
mysql.restore.path=${MYSQL_PATH:/usr/local/bin/mysql}  # default value if the env var is not set

spring.neo4j.uri=neo4j+s://dd941308.databases.neo4j.io
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=mQIgoZTfoF0pl3VbnDCkAxR_TNVGZanmmZKUgyRcBeI

spring.mandatory-file-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.http.encoding.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hadilbelhaj67@gmail.com
spring.mail.password=hgxa lpzb pdup wkvz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.frontend-url=http://localhost:4200
prediction.service.url=http://localhost:5000/predict
